name: CI - Build & Validate

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  # ============================================
  # Lint Check
  # ============================================
  lint:
    name: 🔍 Lint
    runs-on: ubuntu-latest
    container:
      image: node:20-alpine
    steps:
      - name: Install git
        run: apk add --no-cache git

      - name: Checkout code
        run: |
          git clone --depth 1 ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git .
          git checkout ${GITHUB_SHA}

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npm run db:generate

      - name: Run ESLint
        run: npm run lint

  # ============================================
  # Type Check
  # ============================================
  type-check:
    name: 📝 Type Check
    runs-on: ubuntu-latest
    container:
      image: node:20-alpine
    steps:
      - name: Install git
        run: apk add --no-cache git

      - name: Checkout code
        run: |
          git clone --depth 1 ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git .
          git checkout ${GITHUB_SHA}

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npm run db:generate

      - name: Run TypeScript check
        run: npm run type-check

  # ============================================
  # Build
  # ============================================
  build:
    name: 🏗️ Build
    runs-on: ubuntu-latest
    needs: [lint, type-check]
    container:
      image: node:20-alpine
    steps:
      - name: Install git
        run: apk add --no-cache git

      - name: Checkout code
        run: |
          git clone --depth 1 ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git .
          git checkout ${GITHUB_SHA}

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npm run db:generate

      - name: Build all packages
        run: npm run build

  # ============================================
  # Security Audit
  # ============================================
  security-audit:
    name: 🔒 Security Audit
    runs-on: ubuntu-latest
    continue-on-error: true
    container:
      image: node:20-alpine
    steps:
      - name: Install git
        run: apk add --no-cache git

      - name: Checkout code
        run: |
          git clone --depth 1 ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git .
          git checkout ${GITHUB_SHA}

      - name: Run npm audit
        run: npm audit --audit-level=high || true
