name: CD - Deploy to Production

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  # ============================================
  # Build & Validate
  # ============================================
  validate:
    name: ✅ Validate Build
    runs-on: ubuntu-latest
    container:
      image: node:20-alpine
    steps:
      - name: Install git
        run: apk add --no-cache git

      - name: Checkout code
        run: |
          git clone --depth 1 ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git .
          git checkout ${GITHUB_SHA}

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npm run db:generate

      - name: Run lint
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Build
        run: npm run build

  # ============================================
  # Deploy to Production
  # ============================================
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    needs: validate
    container:
      image: alpine:latest
    
    steps:
      - name: Install SSH client
        run: apk add --no-cache openssh-client curl

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy and build on server
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'ENDSSH'
            set -e
            
            DEPLOY_PATH="${{ secrets.DEPLOY_PATH }}"
            DEPLOY_PATH="${DEPLOY_PATH:-/opt/unpload}"
            
            echo "📂 Navigating to deployment directory..."
            cd "$DEPLOY_PATH"
            
            echo "📥 Pulling latest code..."
            git fetch origin main
            git reset --hard origin/main
            
            echo "🏗️ Building Docker images locally..."
            docker compose --env-file .env -f docker/docker-compose.prod.yml build
            
            echo "🗃️ Starting database and waiting for it to be ready..."
            docker compose --env-file .env -f docker/docker-compose.prod.yml up -d db
            
            # Wait for database to be healthy
            echo "⏳ Waiting for database to be healthy..."
            for i in 1 2 3 4 5 6 7 8 9 10; do
              if docker inspect --format='{{.State.Health.Status}}' unpload-db 2>/dev/null | grep -q "healthy"; then
                echo "✅ Database is healthy!"
                break
              fi
              echo "  Attempt $i/10 - waiting..."
              sleep 3
            done
            
            echo "🔧 Running schema sync..."
            docker compose --env-file .env -f docker/docker-compose.prod.yml run --rm api npx prisma db push --accept-data-loss
            
            echo "🚀 Starting all services..."
            docker compose --env-file .env -f docker/docker-compose.prod.yml up -d --remove-orphans
            
            echo "🧹 Cleaning up old images..."
            docker image prune -f
            
            echo "✅ Deployment complete!"
          ENDSSH

      - name: Health Check
        run: |
          echo "⏳ Waiting for services to be ready..."
          sleep 20
          
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'ENDSSH'
            for i in 1 2 3 4 5; do
              # Check via Caddy (port 8080)
              if curl -sf "http://localhost:8080/api/health" > /dev/null 2>&1; then
                echo "✅ Health check passed!"
                exit 0
              fi
              echo "Attempt $i/5 failed, retrying in 5s..."
              sleep 5
            done
            echo "❌ Health check failed after 5 attempts"
            # Show container logs for debugging
            docker logs unpload-api --tail 20 2>&1 || true
            docker logs unpload-caddy --tail 20 2>&1 || true
            exit 1
          ENDSSH

      - name: Cleanup SSH key
        if: always()
        run: rm -f ~/.ssh/deploy_key
