name: Deploy to Production

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  workflow_dispatch:

env:
  APP_NAME: unpload
  DEPLOY_PATH: /opt/unpload

jobs:
  # ============================================
  # BUILD: Docker Images
  # ============================================
  build:
    name: ðŸ—ï¸ Build Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        run: |
          docker version
          echo "Docker is ready"

      - name: Extract version
        id: version
        run: |
          if echo "${{ github.ref }}" | grep -q "refs/tags/"; then
            VERSION=$(echo "${{ github.ref }}" | sed 's|refs/tags/v||')
          else
            VERSION="latest"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"

      - name: Build API image
        run: |
          docker build \
            --build-arg NODE_ENV=production \
            -t unpload-api:${{ steps.version.outputs.version }} \
            -f docker/Dockerfile.api .
          echo "âœ… API image built"

      - name: Build Web image
        run: |
          docker build \
            --build-arg NODE_ENV=production \
            -t unpload-web:${{ steps.version.outputs.version }} \
            -f docker/Dockerfile.web .
          echo "âœ… Web image built"

      - name: Save images
        run: |
          mkdir -p ./images
          docker save unpload-api:${{ steps.version.outputs.version }} | gzip > ./images/unpload-api.tar.gz
          docker save unpload-web:${{ steps.version.outputs.version }} | gzip > ./images/unpload-web.tar.gz
          ls -lh ./images/

      - name: Upload images as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: ./images/
          retention-days: 1

  # ============================================
  # DEPLOY: Transfer and Start
  # ============================================
  deploy:
    name: ðŸš€ Deploy to Server
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download images
        uses: actions/download-artifact@v4
        with:
          name: docker-images
          path: ./images

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.DEPLOY_PORT || 22 }} ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts 2>/dev/null || true

      - name: Transfer images to server
        run: |
          scp -P ${{ secrets.DEPLOY_PORT || 22 }} \
            ./images/*.tar.gz \
            ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/tmp/

      - name: Transfer compose file
        run: |
          scp -P ${{ secrets.DEPLOY_PORT || 22 }} \
            docker/docker-compose.prod.yml \
            ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/tmp/docker-compose.yml

      - name: Deploy on server
        run: |
          ssh -p ${{ secrets.DEPLOY_PORT || 22 }} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "
            set -e
            echo 'ðŸ“¦ Loading Docker images...'
            sudo docker load < /tmp/unpload-api.tar.gz
            sudo docker load < /tmp/unpload-web.tar.gz
            
            echo 'ðŸ“ Setting up application...'
            sudo mkdir -p ${{ env.DEPLOY_PATH }}
            sudo cp /tmp/docker-compose.yml ${{ env.DEPLOY_PATH }}/docker-compose.yml
            
            echo 'ðŸš€ Starting services...'
            cd ${{ env.DEPLOY_PATH }}
            sudo docker compose up -d --remove-orphans
            
            echo 'â³ Waiting for services...'
            sleep 10
            
            echo 'ðŸ§¹ Cleaning up...'
            rm -f /tmp/unpload-*.tar.gz /tmp/docker-compose.yml
            sudo docker system prune -f || true
            
            echo 'âœ… Deployment complete!'
          "

  # ============================================
  # POST-DEPLOY: Health Check
  # ============================================
  health-check:
    name: ðŸ¥ Health Check
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Wait for services
        run: sleep 15

      - name: Check API health
        run: |
          for i in 1 2 3 4 5; do
            if curl -sf http://${{ secrets.DEPLOY_HOST }}:4000/api/health; then
              echo "âœ… API is healthy!"
              exit 0
            fi
            echo "Attempt $i failed, retrying in 10s..."
            sleep 10
          done
          echo "âš ï¸ Health check failed"
        continue-on-error: true

  # ============================================
  # DATABASE: Run Migrations
  # ============================================
  migrate:
    name: ðŸ—„ï¸ Database Migration
    runs-on: ubuntu-latest
    needs: [health-check]
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.DEPLOY_PORT || 22 }} ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts 2>/dev/null || true

      - name: Run migrations
        run: |
          ssh -p ${{ secrets.DEPLOY_PORT || 22 }} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "
            cd ${{ env.DEPLOY_PATH }}
            sudo docker compose exec -T api npx prisma db push --accept-data-loss || echo 'Migration skipped'
            echo 'âœ… Database migration complete'
          "

  # ============================================
  # SUMMARY
  # ============================================
  deploy-success:
    name: ðŸŽ‰ Deployment Complete
    runs-on: ubuntu-latest
    needs: [deploy, health-check, migrate]
    if: success()
    steps:
      - name: Deployment Summary
        run: |
          echo "=========================================="
          echo "ðŸŽ‰ DEPLOYMENT SUCCESSFUL!"
          echo "=========================================="
          echo "Host: ${{ secrets.DEPLOY_HOST }}"
          echo "=========================================="
