name: CD - Deploy to Production

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  # ============================================
  # Build & Validate
  # ============================================
  validate:
    name: ✅ Validate Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Generate Prisma Client
        run: npm run db:generate

      - name: Build
        run: npm run build

  # ============================================
  # Deploy to Production
  # ============================================
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    needs: validate
    environment: ${{ github.event.inputs.environment || 'production' }}
    
    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy and build on server
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'ENDSSH'
            set -e
            
            DEPLOY_PATH="${{ secrets.DEPLOY_PATH }}"
            DEPLOY_PATH="${DEPLOY_PATH:-/opt/unpload}"
            
            echo "📂 Navigating to deployment directory..."
            cd "$DEPLOY_PATH"
            
            echo "📥 Pulling latest code..."
            git fetch origin main
            git reset --hard origin/main
            
            echo "🏗️ Building Docker images locally..."
            docker compose -f docker/docker-compose.prod.yml build
            
            echo "🗃️ Running database migrations..."
            docker compose -f docker/docker-compose.prod.yml run --rm api npx prisma migrate deploy || true
            
            echo "🚀 Starting services..."
            docker compose -f docker/docker-compose.prod.yml up -d --remove-orphans
            
            echo "🧹 Cleaning up old images..."
            docker image prune -f
            
            echo "✅ Deployment complete!"
          ENDSSH

      - name: Health Check
        run: |
          echo "⏳ Waiting for API to be ready..."
          sleep 15
          
          ssh -i ~/.ssh/deploy_key ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'ENDSSH'
            for i in 1 2 3 4 5; do
              if curl -sf "http://localhost:4000/api/health" > /dev/null 2>&1; then
                echo "✅ Health check passed!"
                exit 0
              fi
              echo "Attempt $i/5 failed, retrying in 5s..."
              sleep 5
            done
            echo "❌ Health check failed after 5 attempts"
            exit 1
          ENDSSH

      - name: Cleanup SSH key
        if: always()
        run: rm -f ~/.ssh/deploy_key
