name: CD - Deploy to Production

on:
  workflow_run:
    workflows: ["CD - Build & Push Docker Images"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

env:
  REGISTRY: lab.unishadow.ovh
  IMAGE_PREFIX: unishadow/unpload

jobs:
  # ============================================
  # Deploy to Production
  # ============================================
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    environment: ${{ github.event.inputs.environment || 'production' }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH || '/opt/unpload' }}
        run: |
          ssh $DEPLOY_USER@$DEPLOY_HOST << 'ENDSSH'
            set -e
            
            echo "📂 Navigating to deployment directory..."
            cd ${{ env.DEPLOY_PATH || '/opt/unpload' }}
            
            echo "🔄 Pulling latest images..."
            docker compose -f docker/docker-compose.prod.yml pull
            
            echo "🗃️ Running database migrations..."
            docker compose -f docker/docker-compose.prod.yml run --rm api npx prisma migrate deploy || true
            
            echo "🚀 Starting services with rolling update..."
            docker compose -f docker/docker-compose.prod.yml up -d --remove-orphans
            
            echo "🧹 Cleaning up old images..."
            docker image prune -f
            
            echo "✅ Deployment complete!"
          ENDSSH

      - name: Health Check
        env:
          API_URL: ${{ secrets.API_URL || 'http://localhost:4000' }}
        run: |
          echo "⏳ Waiting for API to be ready..."
          sleep 10
          
          for i in {1..5}; do
            if curl -sf "${{ env.API_URL }}/api/health" > /dev/null 2>&1; then
              echo "✅ Health check passed!"
              exit 0
            fi
            echo "Attempt $i/5 failed, retrying in 5s..."
            sleep 5
          done
          
          echo "❌ Health check failed after 5 attempts"
          exit 1

      - name: Rollback on failure
        if: failure()
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH || '/opt/unpload' }}
        run: |
          echo "🔄 Rolling back to previous version..."
          ssh $DEPLOY_USER@$DEPLOY_HOST << 'ENDSSH'
            cd ${{ env.DEPLOY_PATH || '/opt/unpload' }}
            docker compose -f docker/docker-compose.prod.yml down
            docker compose -f docker/docker-compose.prod.yml up -d --remove-orphans
          ENDSSH

      - name: Notify Discord - Success
        if: success()
        uses: sarisia/actions-status-discord@v1
        continue-on-error: true
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: success
          title: "🚀 Deployment Successful"
          description: |
            **Environment:** ${{ github.event.inputs.environment || 'production' }}
            **Commit:** `${{ github.sha }}`
            **Branch:** `${{ github.ref_name }}`
          color: 0x00ff00

      - name: Notify Discord - Failure
        if: failure()
        uses: sarisia/actions-status-discord@v1
        continue-on-error: true
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: failure
          title: "❌ Deployment Failed"
          description: |
            **Environment:** ${{ github.event.inputs.environment || 'production' }}
            **Commit:** `${{ github.sha }}`
            **Branch:** `${{ github.ref_name }}`
            
            Check the workflow logs for details.
          color: 0xff0000

  # ============================================
  # Deployment Summary
  # ============================================
  summary:
    name: 📋 Deployment Summary
    runs-on: ubuntu-latest
    needs: deploy
    if: always()
    steps:
      - name: Generate summary
        run: |
          echo "## 🚀 Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Property | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Status | ${{ needs.deploy.result == 'success' && '✅ Success' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Environment | ${{ github.event.inputs.environment || 'production' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Commit | \`${{ github.sha }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| Branch | \`${{ github.ref_name }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| Triggered by | ${{ github.event_name }} |" >> $GITHUB_STEP_SUMMARY
