name: Deploy

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

env:
  APP_NAME: unpload
  DEPLOY_PATH: /opt/unpload

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version
        id: version
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=latest" >> $GITHUB_OUTPUT
          fi

      # Build images locally on the runner
      - name: Build Docker images
        run: |
          docker build -t unpload-api:${{ steps.version.outputs.VERSION }} -f docker/Dockerfile.api .
          docker build -t unpload-web:${{ steps.version.outputs.VERSION }} -f docker/Dockerfile.web .

      # Save images to tar files
      - name: Save Docker images
        run: |
          mkdir -p ./build
          docker save unpload-api:${{ steps.version.outputs.VERSION }} | gzip > ./build/unpload-api.tar.gz
          docker save unpload-web:${{ steps.version.outputs.VERSION }} | gzip > ./build/unpload-web.tar.gz

      # Copy images and compose files to target server via SSH
      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT || 22 }}
          source: "build/*.tar.gz,docker/docker-compose.prod.yml,apps/api/prisma/schema.prisma"
          target: "/tmp/unpload-deploy"
          strip_components: 0

      # Load images and start containers on target
      - name: Start containers on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT || 22 }}
          script: |
            set -e
            
            echo "ðŸ“¦ Loading Docker images..."
            docker load < /tmp/unpload-deploy/build/unpload-api.tar.gz
            docker load < /tmp/unpload-deploy/build/unpload-web.tar.gz
            
            echo "ðŸ“ Setting up deploy directory..."
            sudo mkdir -p ${{ env.DEPLOY_PATH }}
            sudo cp /tmp/unpload-deploy/docker/docker-compose.prod.yml ${{ env.DEPLOY_PATH }}/docker-compose.yml
            sudo cp -r /tmp/unpload-deploy/apps/api/prisma ${{ env.DEPLOY_PATH }}/
            
            echo "ðŸ”§ Updating image tags..."
            cd ${{ env.DEPLOY_PATH }}
            sudo sed -i 's|unpload-api:.*|unpload-api:${{ steps.version.outputs.VERSION }}|g' docker-compose.yml
            sudo sed -i 's|unpload-web:.*|unpload-web:${{ steps.version.outputs.VERSION }}|g' docker-compose.yml
            
            echo "ðŸš€ Starting containers..."
            sudo docker compose up -d --remove-orphans
            
            echo "ðŸ—‘ï¸ Cleaning up..."
            rm -rf /tmp/unpload-deploy
            sudo docker system prune -f
            
            echo "âœ… Deployed UnPload ${{ steps.version.outputs.VERSION }}"

  # Run database migrations after deploy
  migrate:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Run database migrations
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT || 22 }}
          script: |
            cd ${{ env.DEPLOY_PATH }}
            sudo docker compose exec -T api npx prisma db push --accept-data-loss || true
            echo "âœ… Database migrations complete"
