name: CI - Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

env:
  NODE_VERSION: '20'

jobs:
  # ============================================
  # Unit Tests - API
  # ============================================
  test-api:
    name: 🧪 API Unit Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: unpload_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://test:test@localhost:5432/unpload_test
      JWT_SECRET: test-secret-key-for-testing-only-32chars

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npm run db:generate

      - name: Push database schema
        run: npm run db:push

      - name: Run API tests
        run: npm run test --workspace=@unpload/api
        continue-on-error: true

      - name: Run API tests with coverage
        run: npm run test:cov --workspace=@unpload/api || true

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-coverage
          path: apps/api/coverage
          retention-days: 7

  # ============================================
  # Unit Tests - Web (if configured)
  # ============================================
  test-web:
    name: 🧪 Web Unit Tests
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Web tests
        run: npm run test --workspace=@unpload/web || echo "No tests configured for web"

  # ============================================
  # E2E Tests (Optional)
  # ============================================
  test-e2e:
    name: 🎭 E2E Tests
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [test-api]
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: unpload_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://test:test@localhost:5432/unpload_test
      JWT_SECRET: test-secret-key-for-testing-only-32chars

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npm run db:generate

      - name: Push database schema
        run: npm run db:push

      - name: Run E2E tests
        run: npm run test:e2e --workspace=@unpload/api || echo "No E2E tests configured"
