name: CI - Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  # ============================================
  # Unit Tests - API
  # ============================================
  test-api:
    name: 🧪 API Unit Tests
    runs-on: ubuntu-latest
    container:
      image: node:20-alpine
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: unpload_test

    env:
      DATABASE_URL: postgresql://test:test@postgres:5432/unpload_test
      JWT_SECRET: test-secret-key-for-testing-only-32chars

    steps:
      - name: Install git
        run: apk add --no-cache git

      - name: Checkout code
        run: |
          git clone --depth 1 ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git .
          git checkout ${GITHUB_SHA}

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npm run db:generate

      - name: Push database schema
        run: npm run db:push

      - name: Run API tests
        run: npm run test --workspace=@unpload/api || echo "No tests found"

  # ============================================
  # Unit Tests - Web
  # ============================================
  test-web:
    name: 🧪 Web Unit Tests
    runs-on: ubuntu-latest
    continue-on-error: true
    container:
      image: node:20-alpine
    steps:
      - name: Install git
        run: apk add --no-cache git

      - name: Checkout code
        run: |
          git clone --depth 1 ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git .
          git checkout ${GITHUB_SHA}

      - name: Install dependencies
        run: npm ci

      - name: Run Web tests
        run: npm run test --workspace=@unpload/web || echo "No tests configured for web"

  # ============================================
  # E2E Tests
  # ============================================
  test-e2e:
    name: 🎭 E2E Tests
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [test-api]
    container:
      image: node:20-alpine
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: unpload_test

    env:
      DATABASE_URL: postgresql://test:test@postgres:5432/unpload_test
      JWT_SECRET: test-secret-key-for-testing-only-32chars

    steps:
      - name: Install git
        run: apk add --no-cache git

      - name: Checkout code
        run: |
          git clone --depth 1 ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git .
          git checkout ${GITHUB_SHA}

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npm run db:generate

      - name: Push database schema
        run: npm run db:push

      - name: Run E2E tests
        run: npm run test:e2e --workspace=@unpload/api || echo "No E2E tests configured"
